$(window).load(function () {
	$(".trigger_popup_fricc1").click(function(){
	   $('.hover_bkgr_fricc1').show();
	});
	$('.hover_bkgr_fricc1').click(function(){
		$('.hover_bkgr_fricc1').hide();
	});
	$('.popupCloseButton1').click(function(){
		$('.hover_bkgr_fricc1').hide();
	});
	$(".trigger_popup_fricc2").click(function(){
		$('.hover_bkgr_fricc2').show();
	 });
	 $('.hover_bkgr_fricc2').click(function(){
		 $('.hover_bkgr_fricc2').hide();
	 });
	 $('.popupCloseButton2').click(function(){
		 $('.hover_bkgr_fricc2').hide();
	 });
});